baseURL = 'https://twentyse7en.vercel.app'
languageCode = 'en-us'
paginate = 5


# ------------------------------
theme = "paper"
title = 'Notes'

[params]
  github = 'twentyse7en'
# ------------------------------

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[menu]

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

