baseURL = 'https://twentyse7en.vercel.app'
languageCode = 'en-us'


# ------------------------------
theme = "paper"
title = 'Dive'

[params]
  github = 'twentyse7en'
# ------------------------------

[menu]

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

